version: "3"
services:
  react:
    image: node:18
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: yarn start

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./front/build:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d

  test-nginx:
    image: nginx
    container_name: test-nginx
    ports:
      - 81:80
    volumes:
      - ./docker/test/:/etc/nginx/conf.d
