version: '3'
services:
    nuxt:
        container_name: nuxt
        build: ./docker/nuxt
        volumes:
            - ./project:/app/project
        ports:
            - 5000:3000
        environment:
            - HOST=0.0.0.0
        command: npm run dev

    server:
        build: ./docker/server
        container_name: server
        tty: true
        ports:
            - 8080:8080
        environment:
            LANG: ja_JP.UTF-8
            TZ: Asia/Tokyo
        volumes:
            - ./server/:/go/src/github.com/inatatsu-tatsuhiro/server
            - ./server/:/usr/local/go/src/api

    db:
        build: ./docker/db
        container_name: db
        ports:
            - 3314:3306
        environment:
            TZ: 'Asia/Tokyo'
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
        volumes:
            - ./docker/db/cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/db/mysql_init:/docker-entrypoint-initdb.d
            - ./db:/var/lib/mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
volumes:
  mysql_data:
        
        

